CREATE DATABASE IF NOT EXISTS axis_ranking CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE axis_ranking;
DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  username VARCHAR(60) NOT NULL UNIQUE,
  score INT NOT NULL DEFAULT 0,
  trend TINYINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
DROP TABLE IF EXISTS goals;
CREATE TABLE goals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(160) NOT NULL,
  target_value INT NOT NULL,
  color VARCHAR(16) NOT NULL DEFAULT '#FF72A7'
) ENGINE=InnoDB;
DROP TABLE IF EXISTS goal_progress;
CREATE TABLE goal_progress (
  user_id INT NOT NULL,
  goal_id INT NOT NULL,
  current_value INT NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, goal_id),
  CONSTRAINT fk_gp_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_gp_goal FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE CASCADE
) ENGINE=InnoDB;
DROP TABLE IF EXISTS badges;
CREATE TABLE badges (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  icon VARCHAR(120) NOT NULL,
  position INT NOT NULL DEFAULT 0
) ENGINE=InnoDB;
DROP TABLE IF EXISTS user_badges;
CREATE TABLE user_badges (
  user_id INT NOT NULL,
  badge_id INT NOT NULL,
  earned_at DATETIME NOT NULL,
  PRIMARY KEY (user_id, badge_id),
  CONSTRAINT fk_ub_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_ub_badge FOREIGN KEY (badge_id) REFERENCES badges(id) ON DELETE CASCADE
) ENGINE=InnoDB;
